// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { LastLoginData, LastLoginResponses, LastLoginErrors, PingData, PingResponses, PingErrors, GetDisableCountdownSettingData, GetDisableCountdownSettingResponses, GetDisableCountdownSettingErrors, SetDisableCountdownSettingData, SetDisableCountdownSettingResponses, SetDisableCountdownSettingErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const lastLogin = <ThrowOnError extends boolean = false>(options?: Options<LastLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<LastLoginResponses, LastLoginErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/wscumbcare/api/v1/last-login',
        ...options
    });
};

export const ping = <ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PingResponses, PingErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/wscumbcare/api/v1/ping',
        ...options
    });
};

export const getDisableCountdownSetting = <ThrowOnError extends boolean = false>(options?: Options<GetDisableCountdownSettingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDisableCountdownSettingResponses, GetDisableCountdownSettingErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/wscumbcare/api/v1/settings/disable-countdown',
        ...options
    });
};

export const setDisableCountdownSetting = <ThrowOnError extends boolean = false>(options?: Options<SetDisableCountdownSettingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SetDisableCountdownSettingResponses, SetDisableCountdownSettingErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/wscumbcare/api/v1/settings/disable-countdown',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};