// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { LastLoginError, LastLoginResponse, PingError, PingResponse } from './types.gen';

export const client = createClient(createConfig());

export class WSCUmbCareService {
  public static lastLogin<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
    return (options?.client ?? client).get<LastLoginResponse, LastLoginError, ThrowOnError>({
      ...options,
      url: '/umbraco/wscumbcare/api/v1/last-login'
    });
  }

  public static ping<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
    return (options?.client ?? client).get<PingResponse, PingError, ThrowOnError>({
      ...options,
      url: '/umbraco/wscumbcare/api/v1/ping'
    });
  }
    
}
