// This file is auto-generated by @hey-api/openapi-ts

export type DisableCountdownRequest = {
    disabled: boolean;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type LastLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wscumbcare/api/v1/last-login';
};

export type LastLoginErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type LastLoginResponses = {
    /**
     * OK
     */
    200: string;
};

export type LastLoginResponse = LastLoginResponses[keyof LastLoginResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wscumbcare/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetDisableCountdownSettingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wscumbcare/api/v1/settings/disable-countdown';
};

export type GetDisableCountdownSettingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDisableCountdownSettingResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetDisableCountdownSettingResponse = GetDisableCountdownSettingResponses[keyof GetDisableCountdownSettingResponses];

export type SetDisableCountdownSettingData = {
    body?: DisableCountdownRequest;
    path?: never;
    query?: never;
    url: '/umbraco/wscumbcare/api/v1/settings/disable-countdown';
};

export type SetDisableCountdownSettingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SetDisableCountdownSettingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44301' | (string & {});
};