// This file is auto-generated by @hey-api/openapi-ts

export type LastLoginResponse = (string);

export type LastLoginError = (unknown);

export type PingResponse = (string);

export type PingError = (unknown);
